# .streamlit/secrets.toml


OPENAI_API_KEY = "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"
server = "colabai.database.windows.net"
database = "colabai"
username = "jer88"
password = "DyjNL4qX3g94KiTD"
